// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfuyxdqzbrjrtqlbkbku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdXl4ZHF6YnJqcnRxbGJrYmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTc3NTIsImV4cCI6MjA2NDQ3Mzc1Mn0.2TlmbMETlxDCjUMrd81BY2moYkJnqUMrAQF4kQvdKG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});